// Code generated by github.com/ssmccoy/gqlgen, DO NOT EDIT.

package model

type Dummy struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
