// Code generated by github.com/ssmccoy/gqlgen, DO NOT EDIT.

package out_directive_binding_models

import (
	"github.com/ssmccoy/gqlgen/plugin/modelgen/out_directive_embedding_models"
)

type Molecule struct {
	out_directive_embedding_models.BaseNode
	Elements []out_directive_embedding_models.Element `json:"elements,omitempty"`
}

func (Molecule) IsNode() {}

type Oxygen struct {
	out_directive_embedding_models.BaseElement
	Purity float64 `json:"purity"`
}

func (Oxygen) IsElement() {}

func (Oxygen) IsNode() {}
