package explicitrequires

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/ssmccoy/gqlgen version v1.17.92-dev

import (
	"context"

	"github.com/ssmccoy/gqlgen/plugin/federation/testdata/explicitrequires/generated"
)

// Size is the batch resolver for the size field.
func (r *multiPlanetRequiresNestedResolver) Size(ctx context.Context, objs []*generated.MultiPlanetRequiresNested) ([]int, error) {
	results := make([]int, len(objs))
	for i, obj := range objs {
		results[i] = len(obj.World.Foo)
	}
	return results, nil
}

// MultiPlanetRequiresNested returns generated.MultiPlanetRequiresNestedResolver implementation.
func (r *Resolver) MultiPlanetRequiresNested() generated.MultiPlanetRequiresNestedResolver {
	return &multiPlanetRequiresNestedResolver{r}
}

type multiPlanetRequiresNestedResolver struct{ *Resolver }
