// Code generated by github.com/ssmccoy/gqlgen, DO NOT EDIT.

package unionextension

type Event interface {
	IsEvent()
}

type Like struct {
	From string `json:"from"`
}

func (Like) IsEvent() {}

type Post struct {
	Message string `json:"message"`
}

func (Post) IsEvent() {}

type Query struct {
}
